%% %%{init: {'theme':'default'}}%%
%% graph TD
%%     %% 定义发布者节点
%%     Channel[Channel]
%%     Acceptor[Acceptor]
%%     TcpConnection[TcpConnection]


%%     %% 定义消息主题节点
%%     publish_read((publish_read))
%%     publish_write((publish_write))
%%     publish_close_1((publish_close_1))
%%     publish_error((publish_error))
    
%%     publish_new_connection((publish_new_connection))
%%     publish_message((publish_message))
%%     publish_close_2((publish_close_2))
    

%%     %% 连接发布者到它们发布的主题
%%     Channel -.-> publish_read
%%     Channel -.-> publish_write
%%     Channel -.-> publish_close_1
%%     Channel -.-> publish_error
  
%%     publish_read -.-> Acceptor
%%     publish_read -.-> TcpConnection
%%     publish_write -.-> TcpConnection
%%     publish_close_1 -.->TcpConnection
%%     publish_error -.->TcpConnection
    
%%     Acceptor -.-> publish_new_connection
%%     TcpConnection -.-> publish_message
%%     TcpConnection -.-> publish_close_2
    
%%     publish_new_connection -.-> TcpServer
%%     publish_message -.中介.-> TcpServer -.中介.-> 业务层
%%     publish_close_2 -.-> TcpServer

%%{init: {
    "theme": "default",
    "themeVariables": {
        "fontFamily": "Times New Roman",
        "fontSize": "20px"
    }
}}%%
graph TD
    %% 定义发布者节点
    Channel(Channel)
    Acceptor(Acceptor)
    TcpConnection(TcpConnection)
    TcpServer(TcpServer)


    Channel -.publish_read.-> Acceptor
    Channel -.publish_read.-> TcpConnection
    Channel -.publish_write.-> TcpConnection
    Channel -.publish_close.-> TcpConnection
    Channel -.publish_error.-> TcpConnection
    
    Acceptor -.publish_new_connection.-> TcpServer
    TcpConnection -.publish_message(中介).-> TcpServer
    TcpConnection -.publish_close.-> TcpServer
    
    TcpServer -.publish_message.-> 业务层
