%% %%{init: {'theme':'default'}}%%
%% graph TD
%%     %% 定义发布者节点
%%     Channel[Channel]
%%     Acceptor[Acceptor]
%%     TcpConnection[TcpConnection]


%%     %% 定义消息主题节点
%%     publish_read((publish_read))
%%     publish_write((publish_write))
%%     handle_close_1((handle_close_1))
%%     publish_error((publish_error))
    
%%     publish_on_connect((publish_on_connect))
%%     handle_message((handle_message))
%%     handle_close_2((handle_close_2))
    

%%     %% 连接发布者到它们发布的主题
%%     Channel -.-> publish_read
%%     Channel -.-> publish_write
%%     Channel -.-> handle_close_1
%%     Channel -.-> publish_error
  
%%     publish_read -.-> Acceptor
%%     publish_read -.-> TcpConnection
%%     publish_write -.-> TcpConnection
%%     handle_close_1 -.->TcpConnection
%%     publish_error -.->TcpConnection
    
%%     Acceptor -.-> publish_on_connect
%%     TcpConnection -.-> handle_message
%%     TcpConnection -.-> handle_close_2
    
%%     publish_on_connect -.-> TcpServer
%%     handle_message -.中介.-> TcpServer -.中介.-> 业务层
%%     handle_close_2 -.-> TcpServer

%%{init: {
    "theme": "default",
    "themeVariables": {
        "fontFamily": "Times New Roman",
        "fontSize": "20px"
    }
}}%%
graph TD
    %% 定义发布者节点
    Channel(Channel)
    Acceptor(Acceptor)
    TcpConnection(TcpConnection)
    TcpServer(TcpServer)


    Channel -.publish_read.-> Acceptor
    Channel -.publish_read.-> TcpConnection
    Channel -.publish_write.-> TcpConnection
    Channel -.handle_close.-> TcpConnection
    Channel -.publish_error.-> TcpConnection
    
    Acceptor -.publish_on_connect.-> TcpServer
    TcpConnection -.handle_message(中介).-> TcpServer
    TcpConnection -.handle_close.-> TcpServer
    
    TcpServer -.handle_message.-> 业务层
