%% %%{init: {'theme':'default'}}%%
%% graph TD
%%     %% 定义发布者节点
%%     Channel[Channel]
%%     Acceptor[Acceptor]
%%     TcpConnection[TcpConnection]


%%     %% 定义消息主题节点
%%     handle_read((handle_read))
%%     handle_write((handle_write))
%%     handle_close_1((handle_close_1))
%%     handle_error((handle_error))
    
%%     handle_connect((handle_connect))
%%     handle_message((handle_message))
%%     handle_close_2((handle_close_2))
    

%%     %% 连接发布者到它们发布的主题
%%     Channel -.-> handle_read
%%     Channel -.-> handle_write
%%     Channel -.-> handle_close_1
%%     Channel -.-> handle_error
  
%%     handle_read -.-> Acceptor
%%     handle_read -.-> TcpConnection
%%     handle_write -.-> TcpConnection
%%     handle_close_1 -.->TcpConnection
%%     handle_error -.->TcpConnection
    
%%     Acceptor -.-> handle_connect
%%     TcpConnection -.-> handle_message
%%     TcpConnection -.-> handle_close_2
    
%%     handle_connect -.-> TcpServer
%%     handle_message -.中介.-> TcpServer -.中介.-> 业务层
%%     handle_close_2 -.-> TcpServer

%%{init: {
    "theme": "default",
    "themeVariables": {
        "fontFamily": "Times New Roman",
        "fontSize": "20px"
    }
}}%%
graph TD
    %% 定义发布者节点
    Channel(Channel)
    Acceptor(Acceptor)
    TcpConnection(TcpConnection)
    TcpServer(TcpServer)


    Channel -.handle_read.-> Acceptor
    Channel -.handle_read.-> TcpConnection
    Channel -.handle_write.-> TcpConnection
    Channel -.handle_close.-> TcpConnection
    Channel -.handle_error.-> TcpConnection
    
    Acceptor -.handle_connect.-> TcpServer
    TcpConnection -.handle_message(中介).-> TcpServer
    TcpConnection -.handle_close.-> TcpServer
    
    TcpServer -.handle_message.-> 业务层
