---
id: c79d8915-8c24-4094-b5de-e50897a85f33
---
%%{init: {'theme':'default'}}%%
sequenceDiagram

    participant EventLoop
    participant Poller
    participant Channel
    participant TcpAcceptor
    participant TcpConnection
	
    loop
	EventLoop->>Poller: poller→poll()

    activate Poller
    Poller->>Poller: fill_active_channels()
    deactivate Poller
    
    Poller->>EventLoop: active channels
	EventLoop->>Channel: channel→publish_event()
	Channel->> TcpAcceptor: publish_read()
	Channel->> TcpConnection: publish_read()、close()...
    end
	EventLoop->>Poller: poller→poll()