%% 示例：在代码块顶部配置主题变量
%%{init: {'theme':'forest'}}%%
sequenceDiagram
    title Reactor todou 网络库时序图
    autonumber
    
    participant EventLoop
    participant Poller
    participant Channel
    participant TcpAcceptor
    participant TcpConnection

    loop
        EventLoop->>Poller: 使用 poller 监听发生事件的 channels
        Poller->>EventLoop: 返回发生事件的 channels 给 eventLoop
        EventLoop->>Channel: eventloop 通知 channel 处理回调
        Channel->> TcpAcceptor: 根据事件进行回调
        Channel->> TcpConnection: 根据事件进行回调
    end
    EventLoop->>Poller: 使用 poller 监听发生事件的 channels
