%% %%{init: {'theme':'default'}}%%
%% graph TD
%%     %% 定义发布者节点
%%     Channel[Channel]
%%     Acceptor[Acceptor]
%%     TcpConnection[TcpConnection]


%%     %% 定义消息主题节点
%%     handle_read((handle_read))
%%     handle_write((handle_write))
%%     handle_close_1((handle_close_1))
%%     handle_error((handle_error))
    
%%     handle_connect((handle_connect))
%%     handle_message((handle_message))
%%     handle_close_2((handle_close_2))
    

%%     %% 连接发布者到它们发布的主题
%%     Channel -.-> handle_read
%%     Channel -.-> handle_write
%%     Channel -.-> handle_close_1
%%     Channel -.-> handle_error
  
%%     handle_read -.-> Acceptor
%%     handle_read -.-> TcpConnection
%%     handle_write -.-> TcpConnection
%%     handle_close_1 -.->TcpConnection
%%     handle_error -.->TcpConnection
    
%%     Acceptor -.-> handle_connect
%%     TcpConnection -.-> handle_message
%%     TcpConnection -.-> handle_close_2
    
%%     handle_connect -.-> TcpServer
%%     handle_message -.中介.-> TcpServer -.中介.-> 业务层
%%     handle_close_2 -.-> TcpServer

%%{init: {
    "theme": "default",
    "themeVariables": {
        "fontFamily": "Times New Roman",
        "fontSize": "20px"
    }
}}%%
graph TD
    %% 定义发布者节点
    EventLoop(EventLoop)
    EpollPoller(EpollPoller)
    Channel(Channel)
    Acceptor(Acceptor)
    TcpConnection(TcpConnection)
    Buffer(Buffer)
    TcpServer(TcpServer)
    HttpContext(HttpContext)
    HttpServer(HttpServer)

    EventLoop -.uses.-> EpollPoller
    EpollPoller -.manages.-> Channel
    TcpConnection -.callbacks.-> Channel
    TcpConnection -.has.-> Buffer
    Acceptor -.callbacks.-> Channel
    TcpServer -.manage+callback.-> Acceptor
    TcpServer -.manages+callbacks.-> TcpConnection
    HttpContext -.callsbacks.-> TcpServer
    HttpServer -.manages+callbacks.-> HttpContext
%% EOF %%
